[project]
name = "pymickey"
version = "0.1.8"
description = "Minimal declarative HTTP API testing tool with YAML scenarios"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [
  { name = "Askhat Molkenov", email = "askhat.molkenov@gmail.com" }
]

dependencies = [
  "httpx>=0.27",
  "pyyaml>=6.0",
]

[project.scripts]
pymickey = "pymickey.cli:cli"

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
exclude = ["pymickey_tests*"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "I", "W", "UP", "B", "SIM", "C4", "RUF"]
ignore = ["RUF002", "RUF003"]

[tool.ruff.lint.isort]
force-single-line = true